# 开启 HTTPS 支持，首先应创建 keystore: keytool -keystore mykeys.jks -genkey -alias tomcat -keyalg RSA
#  ssl:
#    key-store: classpath:mykeys.jks
#    key-store-password: spring
#    key-password: spring

# 跟单点登陆相关
#security:
#  oauth2:
#    client:
#      client-id: HirunSystem
#      client-secret: 12345
#      # 获取令牌的地址
#      access-token-uri: http://192.168.37.131:8080/oauth/token
#      # 授权用户被重定向的地址
#      user-authorization-uri: http://192.168.37.131:8080/oauth/authorize
#    resource:
#      # 访问用户信息的地址
#      user-info-uri: http://192.168.37.131:8080/user/me

spring:
  profiles:
    active: dev
  mvc:
    # 所有静态资源访问，路径以 /static/ 为前缀。
    static-path-pattern: /static/**

  cache:
    # 指定缓存类型: none(禁用缓存), simple(用于开发), redis（用于生产）
    type: simple

  redis:
    timeout: 1000
    host: 127.0.0.1
    port: 6379

  # thymeleaf 模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false # 开发模式下设置为 false，避免改了模板还要重启服务器，线上设置为 true，可以提高性能。

  resources:
    cache:
      period: 604800
    chain:
      cache: true
      enabled: true
      strategy:
        content:
          paths: /**
          enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**

  jta:
    atomikos:
      properties:
        default-jta-timeout: 60000
        log-base-dir: ../logs
    transaction-manager-id: tx

#  main:
#    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    default-fetch-size: 512

# 生产 Web 这个开关是关闭的，后台 Task 进程会在命令行设置该参数为 true
scheduling:
  enabled: true

production.mode: false

# mobile系统地址
mhirun.host-port: http://47.105.64.145:8080/

# 图表仓库位置
hirun.icon.store: //at.alicdn.com/t/font_1556215_q1mayt30v4.css
