server:
  port: 8080
  servlet.context-path: /

  # 开启 HTTPS 支持，首先应创建 keystore: keytool -keystore mykeys.jks -genkey -alias tomcat -keyalg RSA
#  ssl:
#    key-store: classpath:mykeys.jks
#    key-store-password: spring
#    key-password: spring


# 日志
logging:
  level:
    root: INFO
    com.baomidou.mybatisplus: INFO
    com.microtomato: DEBUG

spring:
  datasource:
    dynamic:
      druid:
        initial-size: 0
        max-active: 8
        min-idle: 2
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
      primary: hirun_sys # 默认数据源
      datasource:
        hirun_sys:
          type: com.alibaba.druid.pool.DruidDataSource
          username: hirun_sys
          password: 1q1w1e1r
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://39.106.228.124:3306/hirun_sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        hirun_ins:
          type: com.alibaba.druid.pool.DruidDataSource
          username: hirun_ins
          password: 1q1w1e1r
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://39.106.228.124:3306/hirun_ins?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8


  # thymeleaf 模板配置
  thymeleaf.prefix: classpath:/templates/
  thymeleaf.suffix: .html
  thymeleaf.mode: HTML
  thymeleaf.encoding: UTF-8
  thymeleaf.cache: false

  resources.chain.strategy.content.enabled: true
  resources.chain.strategy.content.paths: /**

  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: Asia/Shanghai
  jackson.default-property-inclusion: non_null

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**

rest:
  api:
    prefix: /api/v1.1

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml