server:
  port: 8080
  servlet.context-path: /
  servlet:
    session:
      timeout: PT5H
      cookie:
        name: HIRUN_SID

# 日志
logging:
  level:
    root: info
    com.atomikos.jdbc.nonxa.AtomikosThreadLocalConnection: info
    com.baomidou.dynamic.datasource: info
    com.baomidou.mybatisplus: info
    com.microtomato.hirun: info

# 是否为生产模式
production.mode: true

spring:
  datasource:
    atomikos:
      sys:
        uniqueResourceName: sys
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        user: sys
        password: ENC(viZyjCQosuNPI/YI5a/bkAjnKGT9R5zD)
        minPoolSize: 10
        maxPoolSize: 50
        maxIdleTime: 60
        maxLifetime: 3600
        borrowConnectionTimeout: 5
        maintenanceInterval: 60
        testQuery: SELECT 1

      ins:
        uniqueResourceName: ins
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ins?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        user: ins
        password: ENC(EFtPlR9pOu98f6a1eLlznevxCmlBJH/S)
        minPoolSize: 10
        maxPoolSize: 50
        maxIdleTime: 60
        maxLifetime: 3600
        borrowConnectionTimeout: 5
        maintenanceInterval: 60
        testQuery: SELECT 1

  cache:
    # 指定缓存类型: none(禁用缓存), simple(用于开发), redis（用于生产）
    type: redis

  redis:
    timeout: 1000
    host: 127.0.0.1
    port: 6379

  # thymeleaf 模板配置
  thymeleaf:
    cache: true # 开发模式下设置为 false，避免改了模板还要重启服务器，线上设置为 true，可以提高性能。

  resources:
    cache:
      period: 604800
    chain:
      cache: true
      enabled: true
      strategy:
        content:
          paths: /**
          enabled: true

  session:
    # session 的存储方式，开发模式（本地）：none，生产模式（分布式缓存）：redis
    store-type: redis
    timeout: 1800

# 数据文件位置
hirun.data.path: /home/web/data
hirun.minio.endpoint: http://127.0.0.1:8443
hirun.minio.accessKey: hirun
hirun.minio.secretKey: 1q1w1e1r