server:
  port: 8080
  servlet.context-path: /
  servlet:
    session:
      timeout: PT1H
      cookie:
        name: HIRUN_SID

# 日志
logging:
  level:
    root: info
    com.atomikos.jdbc.nonxa.AtomikosThreadLocalConnection: info
    com.baomidou.dynamic.datasource: info
    com.baomidou.mybatisplus: info
    com.microtomato.hirun: info

# 是否为生产模式
production.mode: true

spring:
  datasource:
    atomikos:
      sys:
        #        uniqueResourceName: sys
        #        driverClassName: com.mysql.cj.jdbc.Driver
        #        url: jdbc:mysql://127.0.0.1:3306/sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        #        user: sys
        #        password: ENC(viZyjCQosuNPI/YI5a/bkAjnKGT9R5zD)
        #        minPoolSize: 20
        #        maxPoolSize: 50
        #        maxIdleTime: 60
        #        maxLifetime: 1200
        #        maintenanceInterval: 60

        unique-resource-name: sys
        min-pool-size: 10
        max-pool-size: 50
        max-lifetime: 20000
        borrow-connection-timeout: 10000
        xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
        xa-properties:
          url: jdbc:mysql://127.0.0.1:3306/sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: sys
          password: ENC(viZyjCQosuNPI/YI5a/bkAjnKGT9R5zD)
          driverClassName: com.mysql.cj.jdbc.Driver
          initialSize: 10
          minIdle: 8
          maxActive: 50
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 30000
          minEvictableIdleTimeMillis: 300000
          numTestsPerEvictionRun: 2
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: false
          validationQuery: select 1
          maxPoolPreparedStatementPerConnectionSize: 20
          filters: stat,slf4j,wall

      ins:
        #        uniqueResourceName: ins
        #        driverClassName: com.mysql.cj.jdbc.Driver
        #        url: jdbc:mysql://127.0.0.1:3306/ins?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        #        user: ins
        #        password: ENC(EFtPlR9pOu98f6a1eLlznevxCmlBJH/S)
        #        minPoolSize: 20
        #        maxPoolSize: 50
        #        maxIdleTime: 60
        #        maxLifetime: 1200
        #        maintenanceInterval: 60

        unique-resource-name: ins
        min-pool-size: 10
        max-pool-size: 50
        max-lifetime: 20000
        borrow-connection-timeout: 10000
        xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
        xa-properties:
          url: jdbc:mysql://127.0.0.1:3306/ins?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: ins
          password: ENC(EFtPlR9pOu98f6a1eLlznevxCmlBJH/S)
          driverClassName: com.mysql.cj.jdbc.Driver
          initialSize: 10
          minIdle: 8
          maxActive: 50
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 30000
          minEvictableIdleTimeMillis: 300000
          numTestsPerEvictionRun: 2
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: false
          validationQuery: select 1
          maxPoolPreparedStatementPerConnectionSize: 20
          filters: stat,slf4j,wall

  cache:
    # 指定缓存类型: none(禁用缓存), simple(用于开发), redis（用于生产）
    type: redis

  redis:
    timeout: 1000
    host: 127.0.0.1
    port: 6379

  # thymeleaf 模板配置
  thymeleaf:
    cache: true # 开发模式下设置为 false，避免改了模板还要重启服务器，线上设置为 true，可以提高性能。

  resources:
    cache:
      period: 604800
    chain:
      cache: true
      enabled: true
      strategy:
        content:
          paths: /**
          enabled: true

  session:
    # session 的存储方式，开发模式（本地）：none，生产模式（分布式缓存）：redis
    store-type: redis
    timeout: 1800

hirun.data.path: /home/web/data